icon_include_package: jsk_rviz_plugins

rviz_service_call:
    buttons:
    - {service_name: "/planning/cancel_route", text: "Cancel Route"}
    - {service_name: "/localization/cancel_pose", text: "Cancel Pose"}
